### ISSUE TITLE
CSIP, SIP, AIP and DIP should be structured in a similar way

### ISSUE THREAD

**Issue by andersbonielsen** [DILCISBoard/E-ARK-DIP#13]
The documents for the different IPs should be standardized so that they are structured in a similar way and the references should keep the same ID for the same element (CSIP7 should always be the same element in all documents).

**Comment by PhillipTommerholt** [comment]
This is a general issue. See it treated here:
https://github.com/DILCISBoard/E-ARK-SIP/issues/31#issuecomment-484022670

**Comment by carlwilson** [comment]
This has been addressed with regard to document structure but it's impossible to keep IDs in sync in this manner I suspect.
