### ISSUE TITLE
Change from CS IP to CSIP

### ISSUE THREAD

**Issue by PhillipTommerholt** [DILCISBoard/E-ARK-DIP#14]
Change CS IP to CSIP.

https://github.com/DILCISBoard/E-ARK-CSIP/pull/424
https://github.com/DILCISBoard/E-ARK-CSIP/issues/229#issuecomment-488402752
https://github.com/DILCISBoard/GroupDocumentation/issues/16

**Comment by carlwilson** [comment]
Closeable @PhillipTommerholt ?

**Comment by PhillipTommerholt** [comment]
It is consistent now :+1:  @carlwilson
