### ISSUE TITLE
Limitation of representations?

### ISSUE THREAD

**Issue by PhillipTommerholt** [DILCISBoard/E-ARK-DIP#8]
This is stated in the DIP specification:
"The DIP specification is limited to include one and only one representation from an AIP (for which many may exist)." 

I don't understand why this is so.

**Comment by kuldaraas** [comment]
Ask Alex for a clear answer :) 

My assumption is that the DIP is aimed to be as simple as possible to the end-user who doesn't know anything about digital preservation or the concept of representations. 

We assume that 99% of access scenarios follow a logic like: 
* make a search (catalogue, full-text, ontology based, etc); 
* select the object you'd like to examine closer; 
* select the format (like: original db dump vs SIARD; doc vs pdf; etc); 
* ask for the object in this format; 
* repository to prepare the DIP; 
* send to user (or user interface / GUI). 

As such -- this majority scenario is much more easily achieved when you limit the DIP to include only one representation --> it's easier to understand by the user and easier to render for the viewer. 

Of course, the 99% assumption is only based on E-ARK participants experiences and not proved by a quantitative study...

**Comment by karinbredenberg** [comment]
I would say that the most common scenario is the one described by Kuldar and that gives without a doubt only one representation. 
The uncommon case is if the DIP is supposed to be an SIP into a new eArchive and thats a special case I'm not sure we should dwell into describe in detail, that needs to be handled by the two eArchives and their agreement on transfer.

**Comment by shsdev** [comment]
I got an additional opinion that this is too restrictive and is being ignored. I also think that there is no reason to limit representations to only one.

**Comment by jmaferreira** [comment]
I argue that the conversion between AIP to DIP to serve the purpose of being a SIP is a poor one. 

The whole goal of the E-ARK AIP is to support the use case of transferring data between repository systems, not to serve as the internal data storage structure for the repository.

This means that if a repository system wants to send full AIPs to another system, they should convert their internal structure to AIPs and send them to the new repository. The process of getting that data into the new system does not necessary follow an ingest process. It should enter via a different way (i.e. reposity migration scenario or succession plan).

**Comment by shsdev** [comment]
**The suggestion is:**

Remove the limitation "The DIP specification is limited to include one and only one representation from an AIP (for which many may exist).". This means that it would be allowed to have 0 or many representations in the DIP.

**Board members acknowledgment of the issue:**
Tick the box in front of you name to indicate that you have looked at the suggestion.
- [] Karin Bredenberg (Kommunalförbundet Sydarkivera, chair)
- [] Anders Bo Nielsen (National Archives of Denmark)
- [ ] Anja Paulič (National Archives of Slovenia)
- [ ] Arne-Kristian Groven (National Archives of Norway)
- [ ] Gregor Zavrsnik (Geoarh)
- [] Janet Anderson (Highbury Research & Development Ltd.)
- [] Maya Bangerter (Swiss Federal Archives)
- [] Miguel Ferreira (KEEP Solutions)
- [] Stephen Mackey (Penwern Limited)
- [] Sven Schlarb (Austrian Institute of Technology)

**Voting**
(Decision making will be carried out on the basis of majority voting by all eligible members of the Board. In the case of a tied vote, decisions will be made at the discretion of the Chair)

Tick the box in front of you name to say yes to the suggestion.
- [] Karin Bredenberg (Kommunalförbundet Sydarkivera, chair)
- [ ] Anders Bo Nielsen (National Archives of Denmark)
- [ ] Anja Paulič (National Archives of Slovenia)
- [ ] Arne-Kristian Groven (National Archives of Norway)
- [ ] Gregor Zavrsnik (Geoarh)
- [] Janet Anderson (Highbury Research & Development Ltd.)
- [ ] Maya Bangerter (Swiss Federal Archives)
- [ ] Miguel Ferreira (KEEP Solutions)
- [] Stephen Mackey (Penwern Limited)
- [] Sven Schlarb (Austrian Institute of Technology)

**Comment by luis100** [comment]
Hello, I agree with @shsdev that it is too restrictive and is being ignored.

Furthermore, I would say that the purpose of a E-ARK DIP is to transfer information to an access portal that would interface with the end user of the target community. The DIP would be a "projection" (in the [relational algebra meaning](https://en.wikipedia.org/wiki/Projection_(relational_algebra))) of the AIP and can have all or part of the data and metadata. It can have several formats/representations given the user needs, but it would be specialized for that user, which  means it can have formats of metadata or representation different from the AIP, it can be redacted to remove personal information, it can enriched with additional documentation that is not in the AIP. A DIP could also refer to multiple AIPs, to serve as an aggregated export. A DIP serves to fullfill the imediate need for information access and is specific for the user accessing it, the user's queries, the user's rights to access information, and the user's technological background.

Given this I would say that there is no reason to restrict the number of representations of a DIP and this can actually be a problem in certain use cases.

**Comment by shsdev** [comment]
The limitation was removed in the new release [v2.2.0](https://github.com/DILCISBoard/E-ARK-DIP/releases/tag/v2.2.0) as part of pull request https://github.com/DILCISBoard/E-ARK-DIP/pull/74 by commit https://github.com/DILCISBoard/E-ARK-DIP/pull/74/commits/701988eb090e9837c7702de2024a8ef5bf573b67
